# -*- coding: utf-8 -*-
"""Sift.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NWj87kke7NpCN6oZ6fInEK5TmJfQwErj
"""

import numpy as np
import pandas as pd
import cv2 as cv
from google.colab.patches import cv2_imshow
from skimage import io
from PIL import Image
import matplotlib.pylab as plt

url = ["https://th.bing.com/th/id/R.fd2bef4a8b6171f78afcea44eb61174b?rik=EcZx7S6dg1Osag&riu=http%3a%2f%2f66.media.tumblr.com%2f1a05c3c0dd84246980068cb66dead267%2ftumblr_o691obyVll1tf2beyo1_500.jpg&ehk=BEtQzHymlw%2fvYa5a8dfJRQaHuB4nhq4ZtqkPanIRqIQ%3d&risl=&pid=ImgRaw&r=0",
       "https://m.economictimes.com/thumb/height-450,width-600,imgsize-1124122,msid-69051386/elephant.jpg"]

image1 = io.imread(url[0])
image2 = io.imread(url[1])
image1 = cv.cvtColor(image1,cv.COLOR_BGR2RGB)
image2 = cv.cvtColor(image2,cv.COLOR_BGR2RGB)

sift = cv.xfeatures2d.SIFT_create()

keypoints_1,descriptors_1 = sift.detectAndCompute(image1,None)
keypoints_2,descriptors_2 = sift.detectAndCompute(image2,None)

bf = cv.BFMatcher(cv.NORM_L1,crossCheck = True)
matches = bf.match(descriptors_1,descriptors_2)

matches = sorted(matches,key = lambda x:x.distance)
matched_img = cv.drawMatches(image1,keypoints_1,image2,keypoints_2,matches[:50],image2,flags=2)

cv2_imshow(matched_img)